name: Upload Generated Files to Repository

on:
  push:
    branches:
      - hot # 监听 hot 分支上的 push 操作

  schedule:
    - cron: '0 0 * * *'   # 每天 08:00 执行（北京时间）
    - cron: '0 5 * * *'   # 每天 13:00 执行（北京时间）
    - cron: '0 9 * * *'   # 每天 17:00 执行（北京时间）

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages。
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出 hot 分支代码
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: hot  # 直接检出 hot 分支
          fetch-depth: 0  # 获取完整历史记录

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install  --no-frozen-lockfile

      - name: Build
        run: pnpm run gen

      # 配置 Git 信息
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 添加生成的文件到 Git
      - name: Add and commit files
        run: |
          git add public/*
          git commit -m "Add generated files from GitHub Actions"

      # 推送更改到仓库
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 提供的 GITHUB_TOKEN
        run: |
          git push origin hot
